[profile.default]
fs_permissions = [
  { access = "readwrite", path = "./addresses" },
  { access = "read", path = "./chainConfigs" },
  { access = "read", path = "./package.json" },
  { access = "readwrite", path = "./deterministicConfig" },
  { access = "read", path = "../shared-contracts/chainConfigs" },
  { access = "readwrite", path = "../shared-contracts/deterministicConfig" }
]
fuzz_runs = 500
libs = ['node_modules']
optimizer = true
optimizer_runs = 500000
out = 'out'
script = 'script'
src = 'src'
solc_version = '0.8.20'
via_ir = true
evm_version = 'paris'

[profile.dev]
optimizer = false
optimizer_runs = 0
via_ir = false

[rpc_endpoints]
goerli = "https://goerli.gateway.tenderly.co/${TENDERLY_KEY}"
sepolia = "https://sepolia.gateway.tenderly.co/${TENDERLY_KEY}"
mainnet = "https://mainnet.gateway.tenderly.co/${TENDERLY_KEY}"
# for optimism, since we are just using this for deployment/fork testing,
# we can use these since they're lower volume.
base = "https://base.gateway.tenderly.co/${TENDERLY_KEY}"
base_goerli = "https://base-goerli.gateway.tenderly.co/${TENDERLY_KEY}"
optimism = "https://optimism.gateway.tenderly.co/${TENDERLY_KEY}"
optimism_goerli = "https://optimism-goerli.gateway.tenderly.co/${TENDERLY_KEY}"
pgn = "https://rpc.publicgoods.network"
pgn_sepolia = "https://sepolia.publicgoods.network"
zora = "https://rpc.zora.energy/${CONDUIT_KEY}"
zora_goerli = "https://testnet.rpc.zora.energy/${CONDUIT_KEY}"
zora_sepolia = "https://sepolia.rpc.zora.energy/${CONDUIT_KEY}"