name: "Setup Node and Foundry"
description: "Setups up node and foundry"
runs:
  using: "composite"
  steps:
    - name: Enable Corepack
      run: corepack enable
      shell: bash

    - name: Install Node.js
      uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4
      with:
        node-version: 22.14.0
        cache: "pnpm"

    - name: Install pnpm
      run: pnpm install --frozen-lockfile
      shell: bash

    - name: Install Foundry
      uses: foundry-rs/foundry-toolchain@82dee4ba654bd2146511f85f0d013af94670c4de
      with:
        version: v1.2.3
