name: "Contracts"

on: "push"

jobs:
  contracts-comments:
    name: Comments
    uses: ./.github/workflows/contract.yml
    secrets: inherit
    with:
      package_folder: packages/comments
      name: Comments
      ignore_coverage_files: '"*lib*" "*mock*"'
      skip_storage_layout: true

  contracts-coins:
    name: Coins
    uses: ./.github/workflows/contract.yml
    secrets: inherit
    with:
      package_folder: packages/coins
      name: Coins
      skip_storage_layout: true
      ignore_coverage_files: '"*test*" "*src/utils/uniswap/*" "*src/libs/CoinLegacy.sol" "*src/deployment/CoinsDeployerBase.sol"'
      coverage_args: "--ir-minimum"
